    <tr>
        <td>
            ~url~
        </td>
        <td>
            ~hitcount~
        </td>
        <td>
            ~avgtimetaken~
        </td>
        <td>
            ~avgqueries~
        </td>
        <td>
            ~avguniquequeries~
        </td>
    </tr>
